services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=Spring'
      - 'MONGO_INITDB_ROOT_PASSWORD='
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
